# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Com(object):
    def setupUi(self, Com):
        Com.setObjectName("Com")
        Com.resize(398, 244)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Com.sizePolicy().hasHeightForWidth())
        Com.setSizePolicy(sizePolicy)
        self.label_8 = QtWidgets.QLabel(Com)
        self.label_8.setGeometry(QtCore.QRect(1, 32, 711, 601))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/image/background.jpg"))
        self.label_8.setObjectName("label_8")
        self.ComSetComboBox = QtWidgets.QComboBox(Com)
        self.ComSetComboBox.setGeometry(QtCore.QRect(230, 47, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.ComSetComboBox.setFont(font)
        self.ComSetComboBox.setStyleSheet("QComboBox{\n"
"    border: 1px solid #511352;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"    background-color: #79215b;\n"
"    padding-left: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px ;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image:url(:/ico/arrow-down.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin-right: 15px;\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    font-size: 12px;\n"
"    border: 1px solid #511352;\n"
"    padding: 5px;\n"
"    background-color: #79215b;\n"
"    outline: 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"     background-color: rgba(61, 17, 46, 50);\n"
"    border-radius: 4px;\n"
"}")
        self.ComSetComboBox.setObjectName("ComSetComboBox")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.ComSetComboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(Com)
        self.pushButton.setGeometry(QtCore.QRect(230, 180, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #511352;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Com)
        self.pushButton_2.setGeometry(QtCore.QRect(300, 180, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #511352;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.ComSetComboBox_2 = QtWidgets.QComboBox(Com)
        self.ComSetComboBox_2.setGeometry(QtCore.QRect(230, 97, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        font.setBold(True)
        self.ComSetComboBox_2.setFont(font)
        self.ComSetComboBox_2.setStyleSheet("QComboBox{\n"
"    border: 1px solid #511352;\n"
"    border-radius: 4px;\n"
"    padding-left: 10px;\n"
"    background-color: #79215b;\n"
"    padding-left: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QComboBox::drop-down{\n"
"    border: 0px ;\n"
"}\n"
"QComboBox::down-arrow{\n"
"    image:url(:/ico/arrow-down.png);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    margin-right: 15px;\n"
"    margin-top: 2px;\n"
"}\n"
"\n"
"QComboBox QListView{\n"
"    font-size: 12px;\n"
"    border: 1px solid #511352;\n"
"    padding: 5px;\n"
"    background-color: #79215b;\n"
"    outline: 0px;\n"
"    border-radius: 4px;\n"
"}\n"
"QComboBox QListView::item:selected{\n"
"     background-color: rgba(61, 17, 46, 50);\n"
"    border-radius: 4px;\n"
"}")
        self.ComSetComboBox_2.setObjectName("ComSetComboBox_2")
        self.ComSetComboBox_2.addItem("")
        self.ComSetComboBox_2.addItem("")
        self.ComSetComboBox_2.addItem("")
        self.ComSetComboBox_2.addItem("")
        self.label = QtWidgets.QLabel(Com)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(40, 40, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Com)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Com)
        QtCore.QMetaObject.connectSlotsByName(Com)

    def retranslateUi(self, Com):
        _translate = QtCore.QCoreApplication.translate
        Com.setWindowTitle(_translate("Com", "Form"))
        self.ComSetComboBox.setItemText(0, _translate("Com", "COM1"))
        self.ComSetComboBox.setItemText(1, _translate("Com", "COM2"))
        self.ComSetComboBox.setItemText(2, _translate("Com", "COM3"))
        self.ComSetComboBox.setItemText(3, _translate("Com", "COM4"))
        self.ComSetComboBox.setItemText(4, _translate("Com", "COM5"))
        self.ComSetComboBox.setItemText(5, _translate("Com", "COM6"))
        self.ComSetComboBox.setItemText(6, _translate("Com", "COM7"))
        self.ComSetComboBox.setItemText(7, _translate("Com", "COM8"))
        self.ComSetComboBox.setItemText(8, _translate("Com", "COM9"))
        self.ComSetComboBox.setItemText(9, _translate("Com", "COM10"))
        self.pushButton.setText(_translate("Com", "Ок"))
        self.pushButton_2.setText(_translate("Com", "Отмена"))
        self.ComSetComboBox_2.setItemText(0, _translate("Com", "115200"))
        self.ComSetComboBox_2.setItemText(1, _translate("Com", "57600"))
        self.ComSetComboBox_2.setItemText(2, _translate("Com", "38400"))
        self.ComSetComboBox_2.setItemText(3, _translate("Com", "9600"))
        self.label.setText(_translate("Com", "Порт"))
        self.label_2.setText(_translate("Com", "Скорость предачи"))

