# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        Form.setMinimumSize(QtCore.QSize(800, 600))
        Form.setMaximumSize(QtCore.QSize(800, 600))
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(30, 289, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 90, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.Prem_1 = QtWidgets.QPushButton(Form)
        self.Prem_1.setEnabled(False)
        self.Prem_1.setGeometry(QtCore.QRect(30, 330, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.Prem_1.setFont(font)
        self.Prem_1.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.Prem_1.setObjectName("Prem_1")
        self.ComSetBtn = QtWidgets.QPushButton(Form)
        self.ComSetBtn.setGeometry(QtCore.QRect(15, 3, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.ComSetBtn.setFont(font)
        self.ComSetBtn.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: transparent;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:rgba(186, 186, 186, 0.25);\n"
"}")
        self.ComSetBtn.setObjectName("ComSetBtn")
        self.AboutBtn = QtWidgets.QPushButton(Form)
        self.AboutBtn.setGeometry(QtCore.QRect(110, 3, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.AboutBtn.setFont(font)
        self.AboutBtn.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: transparent;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:rgba(186, 186, 186, 0.25);\n"
"}")
        self.AboutBtn.setObjectName("AboutBtn")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 37, 800, 600))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/image/background.jpg"))
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(30, 389, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setEnabled(True)
        self.label_3.setGeometry(QtCore.QRect(10, 564, 721, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background: transparent;\n"
"color: white;\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(760, 580, 16, 16))
        self.label_5.setStyleSheet("background: transparent;")
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/ico/wait.png"))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(780, 580, 16, 16))
        self.label_6.setStyleSheet("background: transparent;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/ico/wait.png"))
        self.label_6.setObjectName("label_6")
        self.Prem_2 = QtWidgets.QPushButton(Form)
        self.Prem_2.setEnabled(False)
        self.Prem_2.setGeometry(QtCore.QRect(120, 330, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.Prem_2.setFont(font)
        self.Prem_2.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.Prem_2.setObjectName("Prem_2")
        self.Prem_3 = QtWidgets.QPushButton(Form)
        self.Prem_3.setEnabled(False)
        self.Prem_3.setGeometry(QtCore.QRect(210, 330, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.Prem_3.setFont(font)
        self.Prem_3.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.Prem_3.setObjectName("Prem_3")
        self.Prem_4 = QtWidgets.QPushButton(Form)
        self.Prem_4.setEnabled(False)
        self.Prem_4.setGeometry(QtCore.QRect(300, 330, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.Prem_4.setFont(font)
        self.Prem_4.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.Prem_4.setObjectName("Prem_4")
        self.Prem_5 = QtWidgets.QPushButton(Form)
        self.Prem_5.setEnabled(False)
        self.Prem_5.setGeometry(QtCore.QRect(390, 330, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.Prem_5.setFont(font)
        self.Prem_5.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.Prem_5.setObjectName("Prem_5")
        self.PC_1 = QtWidgets.QPushButton(Form)
        self.PC_1.setEnabled(False)
        self.PC_1.setGeometry(QtCore.QRect(30, 430, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.PC_1.setFont(font)
        self.PC_1.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.PC_1.setObjectName("PC_1")
        self.PC_2 = QtWidgets.QPushButton(Form)
        self.PC_2.setEnabled(False)
        self.PC_2.setGeometry(QtCore.QRect(120, 430, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.PC_2.setFont(font)
        self.PC_2.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.PC_2.setObjectName("PC_2")
        self.PC_3 = QtWidgets.QPushButton(Form)
        self.PC_3.setEnabled(False)
        self.PC_3.setGeometry(QtCore.QRect(210, 430, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.PC_3.setFont(font)
        self.PC_3.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.PC_3.setObjectName("PC_3")
        self.PC_4 = QtWidgets.QPushButton(Form)
        self.PC_4.setEnabled(False)
        self.PC_4.setGeometry(QtCore.QRect(300, 430, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.PC_4.setFont(font)
        self.PC_4.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.PC_4.setObjectName("PC_4")
        self.PC_5 = QtWidgets.QPushButton(Form)
        self.PC_5.setEnabled(False)
        self.PC_5.setGeometry(QtCore.QRect(390, 430, 85, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        font.setBold(True)
        self.PC_5.setFont(font)
        self.PC_5.setStyleSheet("QPushButton{\n"
"        border : 0px;\n"
"        background: #50254d;\n"
"        color:white;\n"
"        border-radius: 8px;\n"
"        pading-down:2px;\n"
"}\n"
"QPushButton:hover{\n"
"        background-color:#390d39;\n"
"}\n"
"QPushButton:disabled{\n"
"        background: #3c1c3a;\n"
"}")
        self.PC_5.setObjectName("PC_5")
        self.label_4.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.Prem_1.raise_()
        self.ComSetBtn.raise_()
        self.AboutBtn.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.Prem_2.raise_()
        self.Prem_3.raise_()
        self.Prem_4.raise_()
        self.Prem_5.raise_()
        self.PC_1.raise_()
        self.PC_2.raise_()
        self.PC_3.raise_()
        self.PC_4.raise_()
        self.PC_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "GUIController PRO"))
        self.label.setText(_translate("Form", "Теплоком ПРЭМ"))
        self.pushButton.setText(_translate("Form", "Установить свзять "))
        self.Prem_1.setText(_translate("Form", "Ячейка 10"))
        self.ComSetBtn.setText(_translate("Form", "Канал связи"))
        self.AboutBtn.setText(_translate("Form", "О прогрмме"))
        self.label_2.setText(_translate("Form", "Питерфлоу РС"))
        self.label_3.setText(_translate("Form", "Ожидание подключения"))
        self.Prem_2.setText(_translate("Form", "Ячейка 8"))
        self.Prem_3.setText(_translate("Form", "Ячейка 6"))
        self.Prem_4.setText(_translate("Form", "Ячейка 4"))
        self.Prem_5.setText(_translate("Form", "Ячейка 2"))
        self.PC_1.setText(_translate("Form", "Ячейка 10"))
        self.PC_2.setText(_translate("Form", "Ячейка 10"))
        self.PC_3.setText(_translate("Form", "Ячейка 10"))
        self.PC_4.setText(_translate("Form", "Ячейка 10"))
        self.PC_5.setText(_translate("Form", "Ячейка 10"))

